// Auto-generated from keywords.csv - DO NOT EDIT MANUALLY
// Run 'npm run generate-keywords' to regenerate

export interface KeywordMapping {
  category: string;
  originalKeywords: string;
  rootKeywords: string;
  accountants: string;
  cpas: string;
  bookkeepers: string;
  accountingFirms: string;
  taxPreparers: string;
  landingPage: string;
  cta: string;
}

// Placeholder - will be generated by build script
export const keywordMappings: KeywordMapping[] = [];
